name: 02-filters-activity-types

on:
  pull_request:
    types:
    - opened
    - synchronize
    branches:
    - main

jobs:
  
  echo:
    runs-on: ubuntu-latest
    steps:
    - run : echo "This is the 02-filters-activity-types workflow running on pull request events."
    
        